[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
egui-macroquad = "0.15.0"
paste = "1.0.15"
rand = { version = "0.9.0", default-features = false, features = ["os_rng"] }
rand_xoshiro = "0.7.0"
thiserror = "2.0.11"
typenum = { version = "1.17.0", features = ["const-generics"] }
ux = "0.1.6"
